export const products = [
  {
    id: 1,
    title: 'Multani Mitti (Fuller\'s Earth)',
    description: 'A natural clay mask for deep cleansing, removing impurities, and achieving a natural glow.',
    price: 9.99,
    discount: 10,
    tag: 'skincare',
    category: 'Natural Beauty',
    images: [
      require('./assets/products/1_1.jpg'),
      require('./assets/products/1_2.jpg'),
    ],
    specifications: {
      'Form': 'Powder',
      'Skin Type': 'Oily, Combination',
      'Weight': '200g',
      'Origin': 'India',
    },
    reviews: [
      { id: 1, user: 'Priya S.', rating: 5, comment: 'Amazing for oily skin! My face feels so clean.' },
      { id: 2, user: 'Rohan M.', rating: 4, comment: 'Good quality product, but a bit messy to use.' },
    ],
  },
  {
    id: 2,
    title: 'Cold-Pressed Almond Oil',
    description: 'A natural, lightweight moisturizer rich in Vitamin E for glowing skin and healthy hair.',
    price: 18.50,
    discount: 0,
    tag: 'oils',
    category: 'Natural Beauty',
    images: [
      require('./assets/products/2_1.jpg'),
      require('./assets/products/2_2.jpg'),
    ],
    specifications: {
      'Type': 'Cold-Pressed',
      'Use': 'Hair & Skin',
      'Volume': '100ml',
      'Ingredients': '100% Pure Almonds',
    },
    reviews: [
      { id: 1, user: 'Anjali K.', rating: 5, comment: 'Makes my hair so soft. Love the natural smell!' },
    ],
  },
  {
    id: 3,
    title: 'Cast Iron Kadhai',
    description: 'A traditional and healthier alternative to non-stick cookware for your daily cooking needs.',
    price: 29.99,
    discount: 5,
    tag: 'cookware',
    category: 'Healthy Kitchen',
    images: [
        require('./assets/products/3_1.jpg'),
        require('./assets/products/3_2.jpg'),
    ],
  },
  {
    id: 4,
    title: 'Natural Alum Stone (Phitkari)',
    description: 'An effective and chemical-free alternative to modern deodorants that works like a charm.',
    price: 7.99,
    discount: 0,
    tag: 'hygiene',
    category: 'Personal Care',
    images: [
        require('./assets/products/4_1.jpg'),
        require('./assets/products/4_2.jpg'),
    ],
  },
  {
    id: 5,
    title: 'Organic Amla Reetha Shikakai Powder',
    description: 'A traditional, all-natural, sulphate-free powder for healthy hair cleansing and growth.',
    price: 14.99,
    discount: 10,
    tag: 'haircare',
    category: 'Personal Care',
    images: [
        require('./assets/products/5_1.jpg'),
        require('./assets/products/5_2.jpg'),
    ],
  },
  {
    id: 6,
    title: 'Ceylon Cinnamon Sticks',
    description: 'A super spice known to help control blood sugar and reduce joint pain; a healthier cinnamon variety.',
    price: 11.5,
    discount: 0,
    tag: 'spices',
    category: 'Superfoods',
    images: [
        require('./assets/products/6_1.jpg'),
        require('./assets/products/6_2.jpg'),
    ],
  },
  {
    id: 7,
    title: 'Pure Saffron Threads',
    description: 'High-quality saffron to lift your mood and help with skin hyperpigmentation.',
    price: 22.0,
    discount: 10,
    tag: 'spices',
    category: 'Superfoods',
    images: [
        require('./assets/products/7_1.jpg'),
        require('./assets/products/7_2.jpg'),
    ],
  },
  {
    id: 8,
    title: 'Kumkumadi Tailam',
    description: 'A classical Ayurvedic facial oil for a natural glow, suitable for most skin types.',
    price: 35.0,
    discount: 15,
    tag: 'oils',
    category: 'Natural Beauty',
    images: [
        require('./assets/products/8_1.jpg'),
        require('./assets/products/8_2.jpg'),
    ],
  },
  {
    id: 9,
    title: 'Pure Aloe Vera Gel',
    description: 'A multipurpose gel for skin and hair, perfect as a natural moisturizer for oily skin.',
    price: 12.99,
    discount: 5,
    tag: 'skincare',
    category: 'Natural Beauty',
    images: [
        require('./assets/products/9_1.jpg'),
        require('./assets/products/9_2.jpg'),
    ],
  },
  {
    id: 10,
    title: 'Homemade Protein Powder Mix',
    description: 'A blend of seeds and nuts to create your own healthy, preservative-free protein powder.',
    price: 19.99,
    discount: 0,
    tag: 'diy',
    category: 'Nutrition',
    images: [
        require('./assets/products/10_1.jpg'),
        require('./assets/products/10_2.jpg'),
    ],
  },
  {
    id: 11,
    title: 'Wooden Cold Pressed Oil',
    description: 'Groundnut oil extracted using traditional wooden press methods to retain nutrients.',
    price: 21.0,
    discount: 10,
    tag: 'oils',
    category: 'Healthy Kitchen',
    images: [
        require('./assets/products/11_1.jpg'),
        require('./assets/products/11_2.jpg'),
    ],
  },
  {
    id: 12,
    title: 'Natural Loofah Scrubber',
    description: 'Exfoliating and biodegradable body scrubber made from dried gourds.',
    price: 8.99,
    discount: 0,
    tag: 'hygiene',
    category: 'Personal Care',
    images: [
        require('./assets/products/12_1.jpg'),
        require('./assets/products/12_2.jpg'),
    ],
  },
  {
    id: 13,
    title: 'Bamboo Toothbrush Pack',
    description: 'Pack of 4 biodegradable toothbrushes with charcoal-infused bristles.',
    price: 15.99,
    discount: 10,
    tag: 'hygiene',
    category: 'Personal Care',
    images: [
        require('./assets/products/13_1.jpg'),
        require('./assets/products/13_2.jpg'),
    ],
  },
  {
    id: 14,
    title: 'Stone-Ground Gram Flour (Besan)',
    description: 'Traditional and gentle facial cleanser used for ages to achieve clear skin.',
    price: 6.5,
    discount: 0,
    tag: 'skincare',
    category: 'Natural Beauty',
    images: [
        require('./assets/products/14_1.jpg'),
        require('./assets/products/14_2.jpg'),
    ],
  },
  {
    id: 15,
    title: 'Himalayan Pink Salt',
    description: 'A healthier, mineral-rich alternative to common table salt for daily cooking.',
    price: 5.99,
    discount: 0,
    tag: 'seasoning',
    category: 'Healthy Kitchen',
    images: [
        require('./assets/products/15_1.jpg'),
        require('./assets/products/15_2.jpg'),
    ],
  },
  {
    id: 16,
    title: 'Ashwagandha Root Powder',
    description: 'An adaptogenic herb known to reduce stress and anxiety, promoting overall wellness.',
    price: 17.99,
    discount: 10,
    tag: 'herbs',
    category: 'Supplements',
    images: [
        require('./assets/products/16_1.jpg'),
        require('./assets/products/16_2.jpg'),
    ],
  },
  {
    id: 17,
    title: 'Organic Jaggery Powder',
    description: 'An unrefined, natural sweetener and a healthy substitute for processed sugar.',
    price: 8.5,
    discount: 0,
    tag: 'sweeteners',
    category: 'Healthy Kitchen',
    images: [
        require('./assets/products/17_1.jpg'),
        require('./assets/products/17_2.jpg'),
    ],
  },
  {
    id: 18,
    title: 'Copper Water Bottle',
    description: 'A stylish bottle for enjoying the health benefits of water stored in copper, as per Ayurveda.',
    price: 28.0,
    discount: 15,
    tag: 'hydration',
    category: 'Healthy Kitchen',
    images: [
        require('./assets/products/18_1.jpg'),
        require('./assets/products/18_2.jpg'),
    ],
  },
  {
    id: 19,
    title: 'Natural Ubtan Body Scrub',
    description: 'A traditional blend of herbs and pulses for exfoliating and de-tanning the skin.',
    price: 21.99,
    discount: 10,
    tag: 'skincare',
    category: 'Natural Beauty',
    images: [
        require('./assets/products/19_1.jpg'),
        require('./assets/products/19_2.jpg'),
    ],
  },
  {
    id: 20,
    title: 'Triphala Juice',
    description: 'A powerful Ayurvedic juice that acts as a natural blood purifier for a glow from within.',
    price: 19.0,
    discount: 5,
    tag: 'juices',
    category: 'Nutrition',
    images: [
        require('./assets/products/20_1.jpg'),
        require('./assets/products/20_2.jpg'),
    ],
  },
];